### ISSUE TITLE
No An Issue But Question

### ISSUE THREAD

**Issue by dguimard** [jalik/router.js#2]
is it possible to route event from :
https://getmdl.io/components/index.html#toggles-section using the router class you provided ?

thanks a lot for any answer

Kind regards
david

**Comment by jalik** [comment]
@dguimard sorry, I did not understand the question (to route event).
What are you trying to do ?

You can basically change a route, then catch that change with a declared route.

**Comment by dguimard** [comment]
hello ,

i wanted to route specific event from material design lite  component, 
 $(".mdl-switch").on("change", function() {
    	   console.log('change');
 //route specific event via the router
}

**Comment by jalik** [comment]
Hi, I am not familiar with MD framework, but it should not be a problem for you to route :
```js
import {Router} from "jk-router";

$(".mdl-switch").on("change", function() {
  // Also available as a global variable via window.Router as fallback
  Router.go("/path/to/route");
}
```

And do not forget to declare your route :
```js
import {Router} from "jk-router";

// Set default target element ID,
// where route content is displayed using document.getElementById(target)
Router.target = "yield";

Router.route("/path/to/route", function() {
  const html = "<div>template content</div>";
  // you will prefer to use a popular templating framework
  // like handlebars/angular or anything else
  // to generate your HTML here.
  this.render(html);
});
```

Then the HTML :
```html
<html>
<head></head>
<body>
  <div id="main">
    <aside id="sidebar"></sidebar>
    <div id="yield"><!-- route content is displayed here by default --></div>
</body>
</html>

**Comment by dguimard** [comment]
thanks a lot man
